package com.mithaq.app.ui.theme

import androidx.compose.runtime.compositionLocalOf

data class MithaqStrings(
    val appName: String,
    val loginHeader: String,
    val emailLabel: String,
    val passwordLabel: String,
    val signIn: String,
    val createAccount: String,
    val newToMithaq: String,
    val registerAccount: String,
    val alreadyHaveAccount: String,
    val searchFilters: String,
    val matchScore: String,
    val waliIntegration: String,
    val instantTranslation: String,
    val dailyChatLimits: String,
    val searchTab: String,
    val chatTab: String,
    val waliTab: String,
    val profileTab: String,
    val inviteWali: String,
    val waliDescription: String,
    val nameLabel: String,
    val waliEmailLabel: String,
    val sendInvitation: String,
    val cancel: String,
    val close: String,
    val selectSect: String,
    val selectPrayer: String,
    val selectModesty: String,
    val selectRelocation: String,
    val polygamyAcceptance: String,
    val registerTitle: String,
    val personalInfo: String,
    val matchPrefs: String,
    val next: String,
    val back: String
)

val EnglishStrings = MithaqStrings(
    appName = "Mithaq",
    loginHeader = "Sign in to continue serious matchmaking",
    emailLabel = "Email Address",
    passwordLabel = "Password",
    signIn = "Sign In",
    createAccount = "Create Account",
    newToMithaq = "New to Mithaq?",
    registerAccount = "Register Account",
    alreadyHaveAccount = "Already have an account?",
    searchFilters = "Advanced Islamic Filters",
    matchScore = "Compatibility Index",
    waliIntegration = "Wali (Guardian) Integration",
    instantTranslation = "In-Chat Translation",
    dailyChatLimits = "Daily Chat Limits",
    searchTab = "Search",
    chatTab = "Chat",
    waliTab = "Wali",
    profileTab = "Profile",
    inviteWali = "Invite Wali",
    waliDescription = "To ensure a serious environment, sisters are invited to link their guardian's email for chaperonage.",
    nameLabel = "Full Name",
    waliEmailLabel = "Guardian's Email Address",
    sendInvitation = "Send Invitation",
    cancel = "Cancel",
    close = "Close",
    selectSect = "Sect",
    selectPrayer = "Prayer Frequency",
    selectModesty = "Preference for Partner",
    selectRelocation = "Relocation Willingness",
    polygamyAcceptance = "Open to Polygamy",
    registerTitle = "Create New Account",
    personalInfo = "Personal Information",
    matchPrefs = "Matchmaking Preferences",
    next = "Next",
    back = "Back"
)

val ArabicStrings = MithaqStrings(
    appName = "ميثاق",
    loginHeader = "سجل دخولك لمتابعة طلب الزواج الجاد",
    emailLabel = "البريد الإلكتروني",
    passwordLabel = "كلمة المرور",
    signIn = "تسجيل الدخول",
    createAccount = "إنشاء حساب",
    newToMithaq = "جديد في ميثاق؟",
    registerAccount = "تسجيل الحساب",
    alreadyHaveAccount = "لديك حساب بالفعل؟",
    searchFilters = "مرشحات البحث الإسلامية",
    matchScore = "نسبة التوافق",
    waliIntegration = "إشراك ولي الأمر (الولي)",
    instantTranslation = "الترجمة الفورية",
    dailyChatLimits = "الحدود اليومية للمحادثات",
    searchTab = "البحث",
    chatTab = "المحادثة",
    waliTab = "الولي",
    profileTab = "الملف الشخصي",
    inviteWali = "دعوة ولي الأمر",
    waliDescription = "لضمان بيئة جادة وآمنة، تُدعى الأخوات لربط البريد الإلكتروني لأولياء أمورهن للمتابعة.",
    nameLabel = "الاسم الكامل",
    waliEmailLabel = "البريد الإلكتروني لولي الأمر",
    sendInvitation = "إرسال الدعوة",
    cancel = "إلغاء",
    close = "إغلاق",
    selectSect = "المذهب / الطائفة",
    selectPrayer = "المحافظة على الصلاة",
    selectModesty = "شروط الزي للمخطوبة",
    selectRelocation = "الاستعداد للانتقال",
    polygamyAcceptance = "قبول التعدد",
    registerTitle = "إنشاء حساب جديد",
    personalInfo = "المعلومات الشخصية",
    matchPrefs = "تفضيلات المطابقة والزواج",
    next = "التالي",
    back = "رجوع"
)

val LocalMithaqStrings = compositionLocalOf { EnglishStrings }
