package com.mithaq.app.navigation

object Routes {
    const val Splash = "splash"
    const val Language = "language"
    const val Oath = "oath"
    const val Entry = "entry"
    const val Login = "login"
    const val Register = "register"
    const val VerifyEmail = "verify_email"
    const val AccountType = "account_type"
    const val OnboardingQuestion = "onboarding_question"
    const val DescriptionHub = "description_hub"
    const val PrivacyEducation = "privacy_education"
    const val PhotoUpload = "photo_upload"
    const val GuardianSetup = "guardian_setup"
    const val PrayerSettings = "prayer_settings"
    const val ProfileCompletion = "profile_completion"
    const val Home = "home"
    const val Matches = "matches"
    const val Search = "search"
    const val Requests = "requests"
    const val ChatList = "chat_list"
    const val ChatDetail = "chat_detail"
    const val Profile = "profile"
    const val ProfileSettings = "profile_settings"
    const val Settings = "settings"
    const val AdminDashboard = "admin_dashboard"
    const val PremiumStore = "premium_store"
    const val MatchDetail = "match_detail"
    const val Questionnaire = "questionnaire"
    const val Statistics = "statistics"
    const val AiMatchmaker = "ai_matchmaker"
}
